/* gwt-stream.js - GWT-RPC (stream version 7) writer / reader for the Cronometer web app (SPEC section 3).
 *
 * Classic script, no modules: attaches everything to window.CMA.gwt.  Requires src/lib/gwt-registry.js
 * (window.CMA.registry, generated by tools/gen_registry.py) to be loaded first - the registry maps every
 * type signature to its wire layout.  CMA.registryStore (src/lib/registry-store.js, SPEC 3.5) may replace
 * CMA.registry at runtime with one rebuilt from the live bundle; it then calls reloadRegistry() so the
 * caches below (sigCache, boxCache) never serve signatures of the previous build.
 *
 * Wire facts, verified against the compiled bundle 0A1C16E148676A90CBB128E4829A562F (2026-09-27), see
 * research/serializers.txt, research/serving-fields-resolved.md and live/all.js:
 *  - request body (x1n/A1n/y1n):  7|0|<nStrings>|<strings...>|<moduleBase idx>|<policy idx>|<service idx>|
 *    <method idx>|<nParams>|<param sig idx>...|<values...>|   Strings are interned by W0n in first-use
 *    order; the header (G1n/YZj) interns moduleBase, policy, interface, method, then the parameter sigs.
 *  - escaping (C1n) with the regex chosen by B1n from the user agent.  Desktop Chrome's UA contains
 *    "webkit", so the real client uses the long webkit class (ESCAPE_RE_WEBKIT below); the plain
 *    /[\u0000\|\\\uD800-\uFFFF]/g branch is the fallback for unknown browsers.  Escapes: \0 \\ \! \uXXXX.
 *  - booleans '1'/'0' (Qs), ints decimal (''+x), doubles ''+x (so 50 not 50.0), longs base64 (T0n/Q0n:
 *    6-bit groups MSB first, alphabet A-Z a-z 0-9 $ _, leading zero groups skipped, 0 -> 'A').
 *  - writeObject (Z0n): null -> 0; already written -> -(k+1); else intern the type signature, register the
 *    object (a.e++) BEFORE its fields, then serialize the fields.
 *  - response: //OK or //EX + JSON array read from the END (h1n): version, flags, string table, payload.
 *  - readObject (U0n): int; <0 back-reference; 0 null; else reserve a slot (push null) BEFORE instantiate,
 *    store the instance, then deserialize its fields.
 */
window.CMA = window.CMA || {};
(function () {
  'use strict';
  const CMA = window.CMA;

  const STRING_SIG = 'java.lang.String/2004016611';   // java.lang CRC: stable across Cronometer deploys
  const SERVICE = 'com.cronometer.shared.rpc.CronometerService';
  const STREAM_VERSION = 7;

  // B1n, webkit branch (what desktop Chrome executes; '\|' in the bundle is the escaped pipe).
  const ESCAPE_RE_WEBKIT = /[\u0000|\\\u0300-\u03FF\u0590-\u05FF\u0600-\u06FF\u0730-\u074A\u07EB-\u07F3\u0940-\u0963\u0980-\u09FF\u0A00-\u0A7F\u0B00-\u0B7F\u0E00-\u0E7F\u0F00-\u0FFF\u1900-\u194F\u1A00-\u1A1F\u1B00-\u1B7F\u1CDA-\u1CDC\u1DC0-\u1DFF\u1F00-\u1FFF\u2000-\u206F\u20D0-\u20FF\u2100-\u214F\u2300-\u23FF\u2A00-\u2AFF\u3000-\u303F\uAAB2-\uAAB4\uD800-\uFFFF]/g;
  // B1n, final else-branch (SPEC 3.1 quotes this one).
  const ESCAPE_RE_DEFAULT = /[\u0000|\\\uD800-\uFFFF]/g;

  // ------------------------------------------------------------------------------------------------
  // registry access
  // ------------------------------------------------------------------------------------------------
  function registry() {
    const r = CMA.registry;
    if (!r || !r.types) throw new Error('GWT: CMA.registry is not loaded (src/lib/gwt-registry.js must precede gwt-stream.js)');
    return r;
  }
  function entryFor(typeSig) {
    const e = registry().types[typeSig];
    if (!e) throw new Error('GWT: unknown type signature ' + typeSig + ' (regenerate src/lib/gwt-registry.js with tools/gen_registry.py)');
    if (e.k === 'unknown') throw new Error('GWT: type ' + typeSig + ' has no usable layout: ' + e.why);
    return e;
  }
  const sigCache = new Map();
  /** 'java.util.ArrayList' -> 'java.util.ArrayList/4159755760' (full signatures pass through). */
  function sig(base) {
    if (typeof base !== 'string') throw new Error('GWT: sig() needs a type name');
    if (base.indexOf('/') >= 0) return base;
    let found = sigCache.get(base);
    if (found) return found;
    const prefix = base + '/';
    const keys = Object.keys(registry().types);
    for (let i = 0; i < keys.length; i++) if (keys[i].startsWith(prefix)) { found = keys[i]; break; }
    if (!found) throw new Error('GWT: no type signature for ' + base + ' in the registry');
    sigCache.set(base, found);
    return found;
  }
  const boxCache = new Map();
  /** box type signature for a primitive kind: 'i' -> java.lang.Integer/... */
  function boxSig(t) {
    let found = boxCache.get(t);
    if (found) return found;
    const types = registry().types;
    const keys = Object.keys(types);
    for (let i = 0; i < keys.length; i++) {
      const e = types[keys[i]];
      if (e.k === 'box' && e.t === t) { found = keys[i]; break; }
    }
    if (!found) throw new Error('GWT: the registry has no java.lang box for kind ' + t);
    boxCache.set(t, found);
    return found;
  }
  /**
   * registryInfo() -> {permutation, policyHash, generatedAt, types, source} of the registry currently active
   * (CMA.registry). `source` is 'runtime' for a registry CMA.registryStore rebuilt from the live bundle (it
   * stamps `source`) and 'bundled' for the generated src/lib/gwt-registry.js; null when none is loaded.
   */
  function registryInfo() {
    const r = CMA.registry;
    if (!r || !r.types || typeof r.types !== 'object') return { permutation: null, policyHash: null, generatedAt: null, types: 0, source: null };
    return {
      permutation: r.permutation ? String(r.permutation).toUpperCase() : null,
      policyHash: r.policyHash ? String(r.policyHash) : null,
      generatedAt: r.generatedAt || null,
      types: Object.keys(r.types).length,
      source: r.source === 'runtime' ? 'runtime' : 'bundled',
    };
  }
  /**
   * reloadRegistry(): forget everything derived from CMA.registry so the next lookup reads the registry now
   * installed (SPEC 3.5: CMA.registryStore swaps CMA.registry when Cronometer deploys a new build). The caches
   * are sigCache (base name -> full signature, behind the lazy CMA.gwt.SIG getters) and boxCache (primitive
   * kind -> java.lang box signature); every other registry read (entryFor, exceptionInfo, simpleParams) is
   * performed per call. Returns registryInfo() of the registry now active.
   */
  function reloadRegistry() {
    sigCache.clear();
    boxCache.clear();
    return registryInfo();
  }
  function describe(v) {
    try { return typeof v === 'bigint' ? v.toString() + 'n' : JSON.stringify(v); } catch (e) { return String(v); }
  }

  // ------------------------------------------------------------------------------------------------
  // longs (T0n / Q0n / S0n / R0n)
  // ------------------------------------------------------------------------------------------------
  const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789$_';
  const B64_INDEX = new Map();
  for (let i = 0; i < 64; i++) B64_INDEX.set(B64[i], i);
  const MAX_SAFE = BigInt(Number.MAX_SAFE_INTEGER);

  function toBigInt(n, what) {
    if (typeof n === 'bigint') return n;
    if (typeof n === 'number' && Number.isInteger(n)) return BigInt(n);
    throw new Error('GWT: ' + (what || 'long') + ' must be an integer Number or a BigInt, got ' + describe(n));
  }
  /** GWT base64 long (T0n): Number or BigInt -> 'A'.. Emits the 11 six-bit groups MSB first (the top group
   *  holds 4 bits), skipping leading zero groups; the last group is always written, so 0 -> 'A'. */
  function encodeLong(n) {
    const v = BigInt.asUintN(64, toBigInt(n));     // two's complement 64-bit, like T0n's hi/lo int split
    let out = '';
    for (let shift = 60n; shift >= 0n; shift -= 6n) {
      const g = Number((v >> shift) & 63n);
      if (out === '' && g === 0 && shift > 0n) continue; // Q0n: c stays false until the first non-zero group
      out += B64[g];
    }
    return out;
  }
  /** Inverse of encodeLong as a signed 64-bit BigInt (S0n accumulates c = c<<6 | R0n(ch) in a long). */
  function decodeLongBig(s) {
    if (typeof s === 'bigint') return BigInt.asIntN(64, s);
    if (typeof s === 'number') return BigInt.asIntN(64, toBigInt(s, 'long token'));
    if (typeof s !== 'string' || s.length === 0 || s.length > 11) throw new Error('GWT: invalid long token ' + describe(s));
    let v = 0n;
    for (let i = 0; i < s.length; i++) {
      const d = B64_INDEX.get(s[i]);
      if (d === undefined) throw new Error('GWT: invalid character in long token ' + describe(s));
      v = (v << 6n) | BigInt(d);
    }
    return BigInt.asIntN(64, v);
  }
  /** base64 string or plain number -> Number when it is a safe integer, else BigInt. */
  function decodeLong(s) {
    const v = decodeLongBig(s);
    return (v >= -MAX_SAFE && v <= MAX_SAFE) ? Number(v) : v;
  }
  function isLongToken(s) {
    return typeof s === 'string' && s.length > 0 && s.length <= 11 && /^[A-Za-z0-9$_]+$/.test(s);
  }

  // ------------------------------------------------------------------------------------------------
  // string escaping (C1n) and its inverse
  // ------------------------------------------------------------------------------------------------
  function escapeString(s, re) {
    return String(s).replace(re || ESCAPE_RE_WEBKIT, function (ch) {
      const c = ch.charCodeAt(0);
      if (c === 0) return '\\0';
      if (c === 92) return '\\\\';
      if (c === 124) return '\\!';
      const h = c.toString(16);                     // lowercase, like Number.toString(16) in C1n
      return '\\u' + '0000'.slice(h.length) + h;
    });
  }
  function unescapeString(s) {
    return String(s).replace(/\\(u[0-9a-fA-F]{4}|[\s\S])/g, function (m, e) {
      if (e.length === 5) return String.fromCharCode(parseInt(e.slice(1), 16));
      if (e === '0') return '\u0000';
      if (e === '!') return '|';
      return e;                                     // '\\' -> '\'; any other escaped char is kept
    });
  }

  // ------------------------------------------------------------------------------------------------
  // value helpers
  // ------------------------------------------------------------------------------------------------
  const TAGS = { s: 's', i: 'i', l: 'l', d: 'd', z: 'z', h: 'h', b: 'b', f: 'f', c: 'c' };
  /** {s:'..'} | {i:n} | {l:..} | {d:x} | {z:b} | {h:n} | {b:n} | {f:x} | {c:..} -> its tag, else null */
  function tagOf(v) {
    if (!v || typeof v !== 'object' || Array.isArray(v) || v instanceof Map || v.$t !== undefined) return null;
    const keys = Object.keys(v);
    return (keys.length === 1 && TAGS[keys[0]]) ? keys[0] : null;
  }
  function unwrap(v) {
    const t = tagOf(v);
    return t ? v[t] : v;
  }
  function isPrimitiveSig(s) { return s === 'I' || s === 'J' || s === 'Z' || s === 'D' || s === 'F' || s === 'B' || s === 'S' || s === 'C'; }

  // ------------------------------------------------------------------------------------------------
  // Encoder: string table + typed tokens (numbers / long strings / string indices)
  // ------------------------------------------------------------------------------------------------
  class Encoder {
    constructor() {
      this.strings = [];
      this.strIndex = new Map();
      this.tokens = [];             // numbers (ints, doubles, 1/0 booleans, string-table indices) and base64 long strings
      this.objIndex = new Map();    // object identity -> index (Z0n: IdentityHashMap a.f)
      this.strObjIndex = new Map(); // String objects written through writeObject: by value (JS strings are === by value)
      this.nObjects = 0;
    }
    intern(s) {                     // W0n: 0 for null, else 1-based index, first use wins
      if (s === null || s === undefined) return 0;
      s = String(s);
      let i = this.strIndex.get(s);
      if (i === undefined) { this.strings.push(s); i = this.strings.length; this.strIndex.set(s, i); }
      return i;
    }
    string(s) { this.tokens.push(this.intern(s)); }
    int(n, what) {
      if (typeof n === 'boolean') n = n ? 1 : 0;
      if (typeof n === 'bigint') n = Number(n);
      if (typeof n !== 'number' || !Number.isInteger(n)) throw new Error('GWT: ' + (what || 'int') + ' must be an integer, got ' + describe(n));
      this.tokens.push(n);
    }
    double(x, what) {
      if (typeof x === 'bigint') x = Number(x);
      if (typeof x !== 'number') throw new Error('GWT: ' + (what || 'double') + ' must be a number, got ' + describe(x));
      // ''+x would put the tokens NaN / Infinity on the wire; the GWT client never produces them from the dialog.
      if (!Number.isFinite(x)) throw new Error('GWT: ' + (what || 'double') + ' must be finite, got ' + describe(x));
      this.tokens.push(x);
    }
    bool(b) { this.tokens.push(b === true || b === 1 || b === '1' ? 1 : 0); }
    long(v, what) {
      if (typeof v === 'string') {   // an id captured from the wire is passed back verbatim (removeServing)
        if (!isLongToken(v)) throw new Error('GWT: ' + (what || 'long') + ' string must be GWT base64 (A-Za-z0-9$_), got ' + describe(v));
        this.tokens.push(v);
      } else {
        this.tokens.push(encodeLong(toBigInt(v, what)));
      }
    }
    char(c, what) {
      if (typeof c === 'string' && c.length === 1) c = c.charCodeAt(0);
      this.int(c, what || 'char');
    }
    prim(kind, v, what) {
      switch (kind) {
        case 'i': case 'b': case 'h': return this.int(unwrap(v), what);
        case 'z': return this.bool(unwrap(v));
        case 'd': case 'f': return this.double(unwrap(v), what);
        case 'l': return this.long(unwrap(v), what);
        case 's': return this.string(unwrap(v));
        case 'c': return this.char(unwrap(v), what);
        case 'o': return this.object(v);
        default: throw new Error('GWT: unsupported field kind ' + describe(kind) + (what ? ' for ' + what : ''));
      }
    }
    /** one RPC parameter written according to its declared signature (w4j: Y0n/v1n/Z0n) */
    param(sigName, v) {
      if (sigName === STRING_SIG) return this.string(unwrap(v));
      if (sigName === 'I' || sigName === 'B' || sigName === 'S' || sigName === 'C') return this.int(unwrap(v), 'param ' + sigName);
      if (sigName === 'J') return this.long(unwrap(v), 'param J');
      if (sigName === 'Z') return this.bool(unwrap(v));
      if (sigName === 'D' || sigName === 'F') return this.double(unwrap(v), 'param ' + sigName);
      return this.object(v);
    }
    /** writeObject (Z0n): null, back-reference, or type index + body. */
    writeObject(typeSig, identity, body) {
      const k = this.objIndex.get(identity);
      if (k !== undefined) { this.tokens.push(-(k + 1)); return; }
      this.objIndex.set(identity, this.nObjects++);   // registered BEFORE the fields are written
      this.tokens.push(this.intern(typeSig));
      body();
    }
    boxed(t, raw) {                   // tagged primitive / JS string in an object slot -> java.lang box
      if (raw === null || raw === undefined) { this.tokens.push(0); return; }
      const bs = boxSig(t);
      if (t === 's') {                // String objects: GWT's IdentityHashMap compares JS strings by value
        const key = String(raw);
        const k = this.strObjIndex.get(key);
        if (k !== undefined) { this.tokens.push(-(k + 1)); return; }
        this.strObjIndex.set(key, this.nObjects++);
        this.tokens.push(this.intern(bs));
        this.string(key);
        return;
      }
      this.nObjects++;                // every other box is a fresh object (no back-reference)
      this.tokens.push(this.intern(bs));
      this.prim(t, raw, 'boxed ' + t);
    }
    object(v) {
      if (v === null || v === undefined) { this.tokens.push(0); return; }
      const tag = tagOf(v);
      if (tag) return this.boxed(tag, v[tag]);
      if (typeof v === 'string') return this.boxed('s', v);
      if (typeof v === 'boolean') return this.boxed('z', v);
      if (typeof v === 'bigint') return this.boxed('l', v);
      if (typeof v === 'number') throw new Error('GWT: a bare number in an object slot is ambiguous; wrap it as {i:n}, {d:x}, {l:n} or {h:n}');
      if (Array.isArray(v)) return this.writeObject(sig('java.util.ArrayList'), v, () => this.listBody(v));
      if (v instanceof Map) return this.writeObject(sig('java.util.HashMap'), v, () => this.mapBody(v));
      if (typeof v !== 'object' || typeof v.$t !== 'string') {
        throw new Error('GWT: cannot serialise ' + describe(v) + ' (expected {$t,f}, {$t,ordinal}, an array, a Map or a tagged primitive)');
      }
      const e = entryFor(v.$t);
      const t = v.$t;
      switch (e.k) {
        case 'class': return this.writeObject(t, v, () => this.classBody(t, e, v));
        case 'enum': return this.writeObject(t, v, () => {
          if (!Number.isInteger(v.ordinal)) throw new Error('GWT: enum ' + t + ' needs an integer ordinal');
          this.int(v.ordinal);
        });
        case 'box': return this.writeObject(t, v, () => this.prim(e.t, Array.isArray(v.f) ? v.f[0] : v.v, t));
        case 'list': case 'arrays': return this.writeObject(t, v, () => this.listBody(v.f, t));
        case 'singleton': return this.writeObject(t, v, () => {
          if (!Array.isArray(v.f) || v.f.length !== 1) throw new Error('GWT: ' + t + ' needs f:[element]');
          this.object(v.f[0]);                                   // B_n: the element only, no size
        });
        case 'empty': return this.writeObject(t, v, () => {});
        case 'set': return this.writeObject(t, v, () => { this.preBody(e, v); this.listBody(v.f, t); });
        case 'map': return this.writeObject(t, v, () => {
          this.preBody(e, v);
          this.mapBody(v.m instanceof Map ? v.m : (Array.isArray(v.f) ? v.f[0] : v.m), t);
        });
        case 'date': return this.writeObject(t, v, () => {
          this.long(v.ms, t + ' ms');
          (e.f || []).forEach((k, i) => this.prim(k, (v.f || [])[i], t + ' field ' + i));
        });
        case 'array': return this.writeObject(t, v, () => {
          const arr = Array.isArray(v.f) ? v.f : v.a;
          if (!Array.isArray(arr)) throw new Error('GWT: ' + t + ' needs f:[elements]');
          this.int(arr.length);
          for (let i = 0; i < arr.length; i++) this.prim(e.e, arr[i], t + '[' + i + ']');
        });
        default: throw new Error('GWT: cannot serialise kind ' + e.k + ' (' + t + ')');
      }
    }
    classBody(t, e, v) {
      const f = Array.isArray(v.f) ? v.f : [];
      if (f.length !== e.f.length) throw new Error('GWT: ' + t + ' expects ' + e.f.length + ' fields, got ' + f.length);
      for (let i = 0; i < f.length; i++) this.prim(e.f[i], f[i], t + ' field ' + i);
    }
    listBody(arr, t) {
      if (!Array.isArray(arr)) throw new Error('GWT: ' + (t || 'list') + ' needs an array of elements');
      this.int(arr.length);
      for (let i = 0; i < arr.length; i++) this.object(arr[i]);
    }
    mapBody(m, t) {
      if (!(m instanceof Map)) throw new Error('GWT: ' + (t || 'map') + ' needs a Map (as the value, or {$t, m: Map})');
      this.int(m.size);
      for (const [k, v] of m) { this.object(k); this.object(v); }
    }
    preBody(e, v) {                   // instantiate-time reads (LinkedHashMap accessOrder, TreeMap comparator, ...)
      const pre = e.pre || [];
      const given = Array.isArray(v.pre) ? v.pre : [];
      for (let i = 0; i < pre.length; i++) {
        let x = given[i];
        if (x === undefined) x = pre[i] === 'z' ? false : pre[i] === 'o' ? null : 0;
        this.prim(pre[i], x, 'pre ' + i);
      }
    }
    /** request body text (x1n): version|flags|nStrings|escaped strings...|tokens...| */
    body() {
      const parts = [STREAM_VERSION, 0, this.strings.length];
      for (let i = 0; i < this.strings.length; i++) parts.push(escapeString(this.strings[i]));
      for (let i = 0; i < this.tokens.length; i++) parts.push(String(this.tokens[i]));   // ''+x for doubles
      return parts.join('|') + '|';
    }
  }

  // ------------------------------------------------------------------------------------------------
  // Decoder over a token source (responses: from the END of the JSON array; requests: forward)
  // ------------------------------------------------------------------------------------------------
  class Decoder {
    constructor(next, strings) {
      this.next = next;
      this.strings = strings;
      this.objects = [];            // a.e: instantiated objects, for back-references
    }
    int(what) {
      const t = this.next();
      const n = typeof t === 'number' ? t : Number(t);
      if (!Number.isFinite(n) || (typeof t === 'string' && t.trim() === '')) throw new Error('GWT: expected an int for ' + (what || 'int') + ', got ' + describe(t));
      return n;
    }
    bool() {                         // responses carry 1/0 (or true/false), request bodies '1'/'0'
      const t = this.next();
      return t === true || t === 1 || t === '1' || t === 'true';
    }
    double(what) {
      const t = this.next();
      const n = Number(t);
      if (Number.isNaN(n) && t !== 'NaN') throw new Error('GWT: expected a double for ' + (what || 'double') + ', got ' + describe(t));
      return n;
    }
    long() {                         // always represented as the GWT base64 string (decodeLong gives the number)
      const t = this.next();
      if (typeof t === 'number' || typeof t === 'bigint') return encodeLong(t);
      if (!isLongToken(t)) throw new Error('GWT: expected a long token, got ' + describe(t));
      return t;
    }
    string() {
      const i = this.int('string index');
      if (i === 0) return null;
      const s = this.strings[i - 1];
      if (s === undefined) throw new Error('GWT: string index ' + i + ' is outside the string table (' + this.strings.length + ')');
      return s;
    }
    char() { return String.fromCharCode(this.int('char')); }
    prim(kind) {
      switch (kind) {
        case 'i': case 'b': case 'h': return this.int();
        case 'z': return this.bool();
        case 'd': case 'f': return this.double();
        case 'l': return this.long();
        case 's': return this.string();
        case 'c': return this.char();
        case 'o': return this.object();
        default: throw new Error('GWT: unsupported field kind ' + describe(kind));
      }
    }
    param(sigName) {
      if (sigName === STRING_SIG) return this.string();
      if (sigName === 'I' || sigName === 'B' || sigName === 'S' || sigName === 'C') return this.int('param ' + sigName);
      if (sigName === 'J') return this.long();
      if (sigName === 'Z') return this.bool();
      if (sigName === 'D' || sigName === 'F') return this.double('param ' + sigName);
      return this.object();
    }
    /** readObject (U0n) */
    object() {
      const idx = this.int('type index');
      if (idx === 0) return null;
      if (idx < 0) {
        const k = -idx - 1;
        if (k >= this.objects.length) throw new Error('GWT: back-reference ' + idx + ' points past the ' + this.objects.length + ' objects read so far');
        return this.objects[k];
      }
      const typeSig = this.strings[idx - 1];
      if (typeSig === undefined) throw new Error('GWT: type index ' + idx + ' is outside the string table');
      const e = entryFor(typeSig);
      const slot = this.objects.length;
      this.objects.push(null);                       // reserve the slot BEFORE instantiate (U0n)
      let value;
      switch (e.k) {
        case 'class': {
          value = { $t: typeSig, f: [] };
          this.objects[slot] = value;
          for (let i = 0; i < e.f.length; i++) value.f.push(this.prim(e.f[i]));
          break;
        }
        case 'enum': value = { $t: typeSig, ordinal: this.int('ordinal') }; break;
        case 'box': value = this.prim(e.t); break;
        case 'list': case 'arrays': case 'set': {
          const pre = (e.pre || []).map((k) => this.prim(k));
          value = [];
          this.objects[slot] = value;
          const n = this.int('size');
          for (let i = 0; i < n; i++) value.push(this.object());
          if (pre.length) value.$pre = pre;
          break;
        }
        case 'singleton': value = [this.object()]; break;       // A_n: element read in instantiate
        case 'empty': value = e.t === 'map' ? new Map() : []; break;
        case 'map': {
          const pre = (e.pre || []).map((k) => this.prim(k));
          value = new Map();
          this.objects[slot] = value;
          const n = this.int('size');
          for (let i = 0; i < n; i++) { const k = this.object(); value.set(k, this.object()); }
          if (pre.length) value.$pre = pre;
          break;
        }
        case 'date': {
          value = { $t: typeSig, ms: decodeLong(this.long()) };
          if (e.f && e.f.length) value.f = e.f.map((k) => this.prim(k));
          break;
        }
        case 'array': {
          value = [];
          this.objects[slot] = value;
          const n = this.int('length');
          for (let i = 0; i < n; i++) value.push(this.prim(e.e));
          break;
        }
        default: throw new Error('GWT: cannot deserialise kind ' + e.k + ' (' + typeSig + ')');
      }
      this.objects[slot] = value;
      return value;
    }
  }

  // ------------------------------------------------------------------------------------------------
  // response text -> array (JSON, with a CSP-safe fallback for pre-version-8 JS literals)
  // ------------------------------------------------------------------------------------------------
  /** Parses a JS array literal (numbers, '..'/".." strings with JS escapes, true/false/null, nested
   *  arrays) without eval; used when JSON.parse rejects a version-7 payload (h1n uses eval for < 8). */
  function parseArrayLiteral(src) {
    let i = 0;
    const n = src.length;
    function fail(msg) { throw new Error('GWT: cannot parse response literal at offset ' + i + ': ' + msg); }
    function ws() { while (i < n && (src[i] === ' ' || src[i] === '\n' || src[i] === '\r' || src[i] === '\t')) i++; }
    function str(q) {
      i++;
      let out = '';
      while (i < n) {
        const c = src[i++];
        if (c === q) return out;
        if (c !== '\\') { out += c; continue; }
        const e = src[i++];
        switch (e) {
          case 'n': out += '\n'; break;
          case 'r': out += '\r'; break;
          case 't': out += '\t'; break;
          case 'b': out += '\b'; break;
          case 'f': out += '\f'; break;
          case 'v': out += '\v'; break;
          case '0': out += '\u0000'; break;
          case 'x': out += String.fromCharCode(parseInt(src.substr(i, 2), 16)); i += 2; break;
          case 'u': out += String.fromCharCode(parseInt(src.substr(i, 4), 16)); i += 4; break;
          default: out += e;                          // \' \" \\ \/ and anything else literal
        }
      }
      fail('unterminated string');
    }
    function value() {
      ws();
      if (i >= n) fail('unexpected end');
      const c = src[i];
      if (c === '[') {
        i++;
        const out = [];
        ws();
        if (src[i] === ']') { i++; return out; }
        for (;;) {
          out.push(value());
          ws();
          if (src[i] === ',') { i++; continue; }
          if (src[i] === ']') { i++; return out; }
          fail('expected , or ]');
        }
      }
      if (c === '"' || c === "'") return str(c);
      const words = [['true', true], ['false', false], ['null', null], ['NaN', NaN], ['Infinity', Infinity], ['-Infinity', -Infinity]];
      for (let w = 0; w < words.length; w++) {
        if (src.startsWith(words[w][0], i)) { i += words[w][0].length; return words[w][1]; }
      }
      const m = /^-?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?/.exec(src.slice(i, i + 64));
      if (!m) fail('unexpected token ' + JSON.stringify(src.slice(i, i + 12)));
      i += m[0].length;
      return Number(m[0]);
    }
    const v = value();
    ws();
    if (i !== n) fail('trailing characters');
    return v;
  }

  function parseResponseText(text) {
    if (typeof text !== 'string') throw new Error('GWT: response is not a string');
    const head = text.slice(0, 4);
    if (head !== '//OK' && head !== '//EX') throw new Error('GWT: not a GWT-RPC response: ' + JSON.stringify(text.slice(0, 60)));
    const js = text.slice(4);
    let arr;
    try { arr = JSON.parse(js); } catch (e) { arr = parseArrayLiteral(js); }
    if (!Array.isArray(arr) || arr.length < 3) throw new Error('GWT: malformed response array');
    const version = arr[arr.length - 1];
    const flags = arr[arr.length - 2];
    const strings = arr[arr.length - 3];
    if (typeof version !== 'number' || version < 5 || version > 8) throw new Error('GWT: unsupported stream version ' + describe(version));
    if (typeof flags !== 'number' || ((flags | 3) ^ 3) !== 0) throw new Error('GWT: unknown response flags ' + describe(flags));
    if (flags & 1) throw new Error('GWT: responses with elided type names are not supported');
    if (!Array.isArray(strings)) throw new Error('GWT: response has no string table');
    return { ok: head === '//OK', version, flags, strings, payload: arr.slice(0, arr.length - 3) };
  }
  function decoderFor(parsed) {
    let i = parsed.payload.length;                    // h1n: a.a = length; every read is a.b[--a.a]
    const d = new Decoder(function () {
      if (i <= 0) throw new Error('GWT: unexpected end of response payload');
      return parsed.payload[--i];
    }, parsed.strings);
    d.remaining = function () { return i; };
    return d;
  }
  function exceptionInfo(ex) {
    if (!ex || typeof ex !== 'object' || !ex.$t) return { type: ex === null ? 'null' : typeof ex, message: null };
    let message = null;
    const e = registry().types[ex.$t];
    if (e && e.k === 'class' && Array.isArray(ex.f)) {    // Throwable deserializers read the detail message as the first string
      const i = e.f.indexOf('s');
      if (i >= 0) message = ex.f[i];
    }
    return { type: ex.$t, message };
  }

  /**
   * readResponse(text[, kind]) -> {ok:true, value} | {ok:false, exception:{type, message, value}, raw}.
   * kind = 'o' (default, readObject), 's', 'i', 'l', 'z', 'd', 'v' (void) per the method's response reader.
   * Throws on malformed input.
   */
  function readResponse(text, kind) {
    const p = parseResponseText(text);
    const d = decoderFor(p);
    if (p.ok) {
      let value = null;
      if (kind !== 'v' && p.payload.length > 0) value = d.prim(kind || 'o');
      return { ok: true, value, version: p.version, flags: p.flags, strings: p.strings, remaining: d.remaining() };
    }
    const ex = d.object();
    const info = exceptionInfo(ex);
    return { ok: false, exception: { type: info.type, message: info.message, value: ex }, raw: text, version: p.version, flags: p.flags };
  }

  // ------------------------------------------------------------------------------------------------
  // request body -> structure
  // ------------------------------------------------------------------------------------------------
  /**
   * parseRequest(body) -> { version, flags, strings, moduleBase, policyHash, service, method, paramSigs,
   *   tokens (raw value tokens), params (decoded values, best effort), paramError, nonce }
   * nonce = the first parameter when its signature is java.lang.String (SPEC 2.1). Throws on malformed input.
   */
  function parseRequest(body) {
    if (typeof body !== 'string') throw new Error('GWT: request body is not a string');
    const toks = body.split('|');
    if (toks.length && toks[toks.length - 1] === '') toks.pop();       // trailing '|'
    const version = Number(toks[0]);
    const flags = Number(toks[1]);
    const n = Number(toks[2]);
    if (!Number.isInteger(version) || !Number.isInteger(n) || n < 0 || toks.length < 3 + n + 5) throw new Error('GWT: malformed GWT-RPC request body');
    const strings = toks.slice(3, 3 + n).map(unescapeString);
    const rest = toks.slice(3 + n);
    let p = 0;
    const d = new Decoder(function () {
      if (p >= rest.length) throw new Error('GWT: unexpected end of request body');
      return rest[p++];
    }, strings);
    const moduleBase = d.string();
    const policyHash = d.string();
    const service = d.string();
    const method = d.string();
    const nParams = d.int('parameter count');
    const paramSigs = [];
    for (let i = 0; i < nParams; i++) paramSigs.push(d.string());
    const tokens = rest.slice(p);
    const params = [];
    let paramError = null;
    try {
      for (let i = 0; i < nParams; i++) params.push(d.param(paramSigs[i]));
    } catch (e) {
      paramError = String(e && e.message || e);
    }
    const nonce = (paramSigs[0] === STRING_SIG && params.length > 0) ? params[0] : null;
    return { version, flags, strings, moduleBase, policyHash, service, method, paramSigs, tokens, params, paramError, nonce };
  }

  /**
   * simpleParams(parsed) -> [{sig, kind, value, simple}] for every parameter of a parseRequest() result.
   * kind: 'string' | 'int' | 'long' | 'bool' | 'double' | 'day' | 'time' | 'object'. Day and Time objects are
   * flattened to {day, month, year} / {h, m, s}; anything else is `simple:false` with the decoded value.
   * capture.js uses it to find userId ints preceded only by simple params (SPEC 2.3).
   */
  function simpleParams(parsed) {
    const out = [];
    const daySig = safeSig('com.cronometer.shared.entries.models.Day');
    const timeSig = safeSig('com.cronometer.shared.entries.models.Time');
    for (let i = 0; i < parsed.paramSigs.length; i++) {
      const s = parsed.paramSigs[i];
      const v = parsed.params[i];
      const item = { sig: s, value: v, simple: true, kind: 'object' };
      if (i >= parsed.params.length) { item.simple = false; item.value = undefined; out.push(item); continue; }
      if (s === STRING_SIG) item.kind = 'string';
      else if (s === 'I' || s === 'B' || s === 'S' || s === 'C') item.kind = 'int';
      else if (s === 'J') item.kind = 'long';
      else if (s === 'Z') item.kind = 'bool';
      else if (s === 'D' || s === 'F') item.kind = 'double';
      else if (v && v.$t === daySig && Array.isArray(v.f)) { item.kind = 'day'; item.value = { day: v.f[0], month: v.f[1], year: v.f[2] }; }
      else if (v && v.$t === timeSig && Array.isArray(v.f)) { item.kind = 'time'; item.value = { h: v.f[0], m: v.f[1], s: v.f[2] }; }
      else if (v === null && (s === daySig || s === timeSig)) { item.kind = s === daySig ? 'day' : 'time'; }
      else item.simple = false;
      out.push(item);
    }
    return out;
  }
  function safeSig(base) { try { return sig(base); } catch (e) { return null; } }

  // ------------------------------------------------------------------------------------------------
  // Writer (SPEC 3.4)
  // ------------------------------------------------------------------------------------------------
  class Writer {
    /** new CMA.gwt.Writer(moduleBase, policyHash[, {service}]) */
    constructor(moduleBase, policyHash, opts) {
      if (typeof moduleBase !== 'string' || !moduleBase) throw new Error('GWT: Writer needs the module base URL');
      if (typeof policyHash !== 'string' || !policyHash) throw new Error('GWT: Writer needs the serialization policy hash');
      this.moduleBase = moduleBase;
      this.policyHash = policyHash;
      this.service = (opts && opts.service) || SERVICE;
    }
    /** .call(method, paramSigs, values) -> request body string (see the file header for the layout). */
    call(method, paramSigs, values) {
      if (typeof method !== 'string' || !method) throw new Error('GWT: call() needs a method name');
      if (!Array.isArray(paramSigs)) throw new Error('GWT: call() needs an array of parameter signatures');
      values = values || [];
      if (values.length !== paramSigs.length) throw new Error('GWT: ' + method + ' expects ' + paramSigs.length + ' values, got ' + values.length);
      const enc = new Encoder();
      enc.string(this.moduleBase);      // YZj: module base, policy hash
      enc.string(this.policyHash);
      enc.string(this.service);         // G1n: interface, method, parameter count
      enc.string(method);
      enc.int(paramSigs.length);
      for (let i = 0; i < paramSigs.length; i++) enc.string(paramSigs[i]);
      for (let i = 0; i < paramSigs.length; i++) enc.param(paramSigs[i], values[i]);
      return enc.body();
    }
  }

  // ------------------------------------------------------------------------------------------------
  // test helpers: response fabrication (inverse of readResponse)
  // ------------------------------------------------------------------------------------------------
  /**
   * encodeResponse(value[, opts]) -> '//OK[...]'. value undefined -> void (empty payload); null -> a null object.
   * opts.kind = 's'|'i'|'l'|'z'|'d' writes a primitive payload; opts.ex = true produces '//EX[...]'.
   */
  function encodeResponse(value, opts) {
    opts = opts || {};
    const enc = new Encoder();
    if (value !== undefined) {
      if (opts.kind && opts.kind !== 'o') enc.prim(opts.kind, value, 'response');
      else enc.object(value);
    }
    const arr = enc.tokens.slice().reverse();          // the client reads from the end
    arr.push(enc.strings, opts.flags || 0, opts.version || STREAM_VERSION);
    return (opts.ex ? '//EX' : '//OK') + JSON.stringify(arr);
  }
  /** encodeException(typeSig, message) -> '//EX[...]' with the message in the Throwable's string slot. */
  function encodeException(typeSig, message) {
    const full = sig(typeSig);
    const e = entryFor(full);
    if (e.k !== 'class') throw new Error('GWT: ' + full + ' is not a class');
    const f = e.f.map((k) => (k === 'z' ? false : k === 'o' || k === 's' ? null : 0));
    const i = e.f.indexOf('s');
    if (i >= 0) f[i] = message === undefined ? null : message;
    return encodeResponse({ $t: full, f }, { ex: true });
  }

  // ------------------------------------------------------------------------------------------------
  // graph helpers
  // ------------------------------------------------------------------------------------------------
  /** walk(value, fn): depth-first over class fields, array elements and Map keys/values; fn(node, path, parent)
   *  is called for every node (primitives included); returning false skips the node's children. Cycle-safe. */
  function walk(value, fn) {
    const seen = new Set();
    (function visit(node, path, parent) {
      const isObj = node !== null && typeof node === 'object';
      if (isObj) { if (seen.has(node)) return; seen.add(node); }
      if (fn(node, path, parent) === false || !isObj) return;
      if (Array.isArray(node)) {
        for (let i = 0; i < node.length; i++) visit(node[i], path.concat(i), node);
      } else if (node instanceof Map) {
        let i = 0;
        for (const [k, v] of node) { visit(k, path.concat('key' + i), node); visit(v, path.concat(typeof k === 'object' ? 'value' + i : k), node); i++; }
      } else if (Array.isArray(node.f)) {
        for (let i = 0; i < node.f.length; i++) visit(node.f[i], path.concat(i), node);
      }
    })(value, [], null);
  }
  /** findMaps(value[, pred]) -> every Map in the graph (for which pred(map) is truthy). */
  function findMaps(value, pred) {
    const out = [];
    walk(value, function (node) { if (node instanceof Map && (!pred || pred(node))) out.push(node); });
    return out;
  }

  // ------------------------------------------------------------------------------------------------
  // exports
  // ------------------------------------------------------------------------------------------------
  const F = {   // SPEC 3.3 field indices
    SERVING: { DAY: 0, ORDER: 4, TIME: 5, USER: 6, GRAMS: 7, FOOD: 8, ID: 9, MEASURE: 10, TRANSLATION: 12 },
    // Measure/1979099908 [d a, z b, i foodId, z d, i measureId, o f, s name, o i, o type, d k]: a = the amount shown
    // before the name when != 1 (qqj), f = the ml Double behind the ' — N ml' label suffix (pqj), k = grams per unit,
    // d = 'Hidden' in the measure editor (the Add Food dialog's VCe drops measures with d === true).
    MEASURE: { AMOUNT: 0, FOOD: 2, HIDDEN: 3, ID: 4, ML: 5, NAME: 6, TYPE: 8, GRAMS: 9 },
    // Food.f (NAME, index 4) is NOT a display name in this build (prototype default '', never read by the app):
    // the name the app shows is the locale Translation's (Rjj), see CMA.plan.foodDisplayName.
    FOOD: { NAME: 4, ID: 7, MEASURES: 11, TRANSLATIONS: 17 },
    DAYINFO: { LIST1: 2, LIST2: 3 },
    USER: { ID: 19, SESSION: 33 },
  };
  const BASES = {   // resolved lazily through sig(): survives a CRC change after regeneration
    STRING: 'java.lang.String', INTEGER: 'java.lang.Integer', ARRAYLIST: 'java.util.ArrayList', HASHMAP: 'java.util.HashMap',
    SINGLETON: 'java.util.Collections$SingletonList', DATE: 'java.util.Date',
    DAY: 'com.cronometer.shared.entries.models.Day', TIME: 'com.cronometer.shared.entries.models.Time',
    SERVING: 'com.cronometer.shared.entries.models.Serving', DAYINFO: 'com.cronometer.shared.entries.models.DayInfo',
    ADD_ENTRY_CHANGE: 'com.cronometer.shared.entries.changes.AddEntryChange',
    ADD_ENTRY_CHANGE_RESULT: 'com.cronometer.shared.entries.changes.AddEntryChangeResult',
    ERROR_ENTRY_CHANGE_RESULT: 'com.cronometer.shared.entries.changes.ErrorEntryChangeResult',
    MEASURE: 'com.cronometer.shared.foods.models.Measure', MEASURE_TYPE: 'com.cronometer.shared.foods.models.Measure$Type',
    FOOD_MEASURES: 'com.cronometer.shared.foods.models.FoodMeasures', FOOD: 'com.cronometer.shared.foods.models.Food',
    FOOD_SOURCE: 'com.cronometer.shared.foods.FoodSource', SEARCH_HIT: 'com.cronometer.shared.foods.models.SearchHit',
    USER: 'com.cronometer.shared.user.models.User', USER_PREFERENCES: 'com.cronometer.shared.user.models.UserPreferences',
    NOT_LOGGED_IN: 'com.cronometer.shared.user.exceptions.NotLoggedInException',
    // Adaptive TDEE reads (rpc.getBiometrics / getCalendarInfo / getCaloriesConsumedAndBurned, research/tdee-critic.md):
    // optional types - registry-builder.js checks them as the 'tdee' feature, never as part of the core bar.
    DAY_QUERY_TYPE: 'com.cronometer.shared.entries.DayQueryType',
    DATA_POINT: 'com.cronometer.shared.charts.models.DataPoint',
    DATA_POINT_ARRAY: '[Lcom.cronometer.shared.charts.models.DataPoint;',
    CALENDAR_INFO: 'com.cronometer.shared.entries.models.CalendarInfo',
    CALENDAR_DAY_INFO: 'com.cronometer.shared.entries.models.CalendarDayInfo',
    DOUBLE_ARRAY: '[D', DOUBLE_ARRAY_2D: '[[D',
  };
  const SIG = {};
  Object.keys(BASES).forEach(function (k) {
    Object.defineProperty(SIG, k, { enumerable: true, get: function () { return sig(BASES[k]); } });
  });

  CMA.gwt = {
    STRING_SIG, SERVICE, STREAM_VERSION, ESCAPE_RE_WEBKIT, ESCAPE_RE_DEFAULT, F, SIG, BASES,
    Writer, Encoder, Decoder,
    encodeLong, decodeLong, decodeLongBig, isLongToken,
    escapeString, unescapeString,
    readResponse, parseResponseText, parseArrayLiteral,
    parseRequest, simpleParams,
    encodeResponse, encodeException,
    findMaps, walk,
    sig, boxSig, entryFor, tagOf,
    reloadRegistry, registryInfo,
  };
})();
